# Generated by Django 6.0.3 on 2026-08-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_telegram_chat_id_user_two_fa_enabled_otpcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpcode',
            name='code',
        ),
        migrations.AddField(
            model_name='otpcode',
            name='code_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
