# Generated by Django 6.0.3 on 2026-03-28 11:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0003_alter_item_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))])),
                ('purchase_marketplace_custom', models.CharField(blank=True, max_length=255)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('9999999999.99'))])),
                ('sell_marketplace_custom', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('inventory', 'In Inventory'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], default='inventory', max_length=20)),
                ('hold_till', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('purchase_marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_trades', to='items.marketplace')),
                ('sell_marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='items.marketplace')),
                ('tags', models.ManyToManyField(blank=True, related_name='trades', to='tradebook.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tradebook_t_user_id_a33e01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='tradebook',
            index=models.Index(fields=['user', 'status'], name='tradebook_t_user_id_8bbba2_idx'),
        ),
        migrations.AddIndex(
            model_name='tradebook',
            index=models.Index(fields=['user', 'item'], name='tradebook_t_user_id_758e8c_idx'),
        ),
    ]
