# Generated by Django 5.2.1 on 2026-03-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_marketplace_custom', models.CharField(max_length=255, null=True)),
                ('sell_date', models.DateField(blank=True, null=True)),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_marketplace_custom', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('inventory', 'In Inventory'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], default='inventory', max_length=20)),
                ('hold_till', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('purchase_marketplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_trades', to='items.marketplace')),
                ('sell_marketplace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='items.marketplace')),
            ],
        ),
    ]
