# Generated by Django 5.2.1 on 2026-03-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_itemlisting_url'),
        ('notebook', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='deals',
            new_name='notebook',
        ),
        migrations.RenameIndex(
            model_name='notebook',
            new_name='notebook_no_user_id_f882be_idx',
            old_name='deals_deals_user_id_27a95d_idx',
        ),
        migrations.RenameIndex(
            model_name='notebook',
            new_name='notebook_no_user_id_2756fd_idx',
            old_name='deals_deals_user_id_b8f341_idx',
        ),
        migrations.RenameIndex(
            model_name='notebook',
            new_name='notebook_no_user_id_cd3da8_idx',
            old_name='deals_deals_user_id_3e3174_idx',
        ),
    ]
