# Generated by Django 5.2.1 on 2026-03-20 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tradebook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tradebook',
            index=models.Index(fields=['user', 'status'], name='tradebook_t_user_id_8bbba2_idx'),
        ),
        migrations.AddIndex(
            model_name='tradebook',
            index=models.Index(fields=['user', 'item'], name='tradebook_t_user_id_758e8c_idx'),
        ),
    ]
