# Generated by Django 6.0.3 on 2026-04-02 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0002_alter_tradebook_sell_marketplace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tag',
            name='tradebook_t_user_id_a33e01_idx',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'user')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'tag'], name='tradebook_t_user_id_993098_idx'),
        ),
    ]
