# Generated by Django 6.0.3 on 2026-03-24 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_name'),
        ('tradebook', '0002_alter_tradebook_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebook',
            name='purchase_marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_trades', to='items.marketplace'),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='purchase_marketplace_custom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='sell_marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='items.marketplace'),
        ),
        migrations.AlterField(
            model_name='tradebook',
            name='sell_marketplace_custom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
