# Generated by Django 6.0.3 on 2026-04-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_name'),
        ('tradebook', '0003_remove_tag_tradebook_t_user_id_a33e01_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebook',
            name='sell_marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='items.marketplace'),
        ),
    ]
