# Generated by Django 6.0.3 on 2026-03-24 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_name'),
        ('tradebook', '0004_alter_tradebook_sell_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebook',
            name='sell_marketplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_trades', to='items.marketplace'),
        ),
    ]
