# Generated by Django 6.0.3 on 2026-08-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradebook', '0004_alter_tradebook_sell_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebook',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
