# Generated by Django 5.2.1 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_site', models.CharField(max_length=50)),
                ('sell_date', models.DateField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sell_site', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deal_complete', models.BooleanField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('item_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'deal_complete'], name='deals_deals_user_id_27a95d_idx'), models.Index(fields=['user', '-time_stamp'], name='deals_deals_user_id_b8f341_idx'), models.Index(fields=['user', 'item_listing'], name='deals_deals_user_id_3e3174_idx')],
            },
        ),
    ]
