# Generated by Django 5.2.1 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=50, null=True)),
                ('source_game', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='item_images/')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='items_items_name_9eb520_idx'), models.Index(fields=['source_game'], name='items_items_source__d47928_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('latest_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('latest_fee', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('price_changed_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=500, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
            ],
            options={
                'indexes': [models.Index(fields=['item'], name='items_iteml_item_id_7671e2_idx'), models.Index(fields=['latest_price'], name='items_iteml_latest__4b5a7d_idx'), models.Index(fields=['last_checked_at'], name='items_iteml_last_ch_1f162d_idx'), models.Index(fields=['item', 'site'], name='items_iteml_item_id_02a08d_idx')],
            },
        ),
    ]
