# Generated by Django 5.2.1 on 2026-03-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('url_base', models.URLField(blank=True)),
                ('api_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_on_market', models.CharField(max_length=255, unique=True)),
                ('quality', models.CharField(max_length=50, null=True)),
                ('source_game', models.CharField(choices=[('CS2', 'counter strike 2'), ('CSGO', 'CS:GO (Legacy)'), ('RUST', 'Rust')], max_length=30)),
                ('image', models.ImageField(null=True, upload_to='item_images/')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='items_item_name_1c746e_idx'), models.Index(fields=['source_game'], name='items_item_source__5a9a13_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('url', models.URLField(max_length=500)),
                ('last_checked_at', models.DateTimeField(auto_now=True, null=True)),
                ('price_changed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.marketplace')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'marketplace'], name='items_iteml_item_id_f7cb52_idx'), models.Index(fields=['current_price'], name='items_iteml_current_f9eba2_idx'), models.Index(fields=['last_checked_at'], name='items_iteml_last_ch_1f162d_idx')],
                'unique_together': {('item', 'marketplace')},
            },
        ),
    ]
