# Generated by Django 5.2.1 on 2026-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlisting',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
