# Generated by Django 5.2.1 on 2026-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='source_game',
            field=models.CharField(choices=[('CS2', 'counter strike 2'), ('RUST', 'Rust')], max_length=30),
        ),
    ]
