# Generated by Django 6.0.3 on 2026-04-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
