# Generated by Django 5.2.6 on 2026-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='next_scrape_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemlisting',
            name='scrape_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='itemlisting',
            index=models.Index(fields=['scrape_priority', 'next_scrape_at'], name='items_iteml_scrape__d1380d_idx'),
        ),
    ]
