# Generated by Django 6.0.3 on 2026-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemlisting_next_scrape_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlisting',
            name='fee_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
