# Generated by Django 5.2.1 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('owned', 'Owned / Holding'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], default='owned', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchased_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hold_end', models.DateTimeField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.items')),
                ('item_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='inventory_i_user_id_b634ec_idx'), models.Index(fields=['user', 'item'], name='inventory_i_user_id_f5e15c_idx'), models.Index(fields=['status'], name='inventory_i_status_2e2af1_idx')],
            },
        ),
        migrations.CreateModel(
            name='soled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('items_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='inventory_s_user_id_c3ad51_idx'), models.Index(fields=['items_listing'], name='inventory_s_items_l_c52638_idx'), models.Index(fields=['sell_date'], name='inventory_s_sell_da_c0f2f1_idx')],
            },
        ),
    ]
