# Generated by Django 5.2.1 on 2026-03-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('owned', 'Owned'), ('listed', 'Listed for Sale'), ('sold', 'Sold')], default='owned', max_length=20),
        ),
    ]
