# Generated by Django 6.0.3 on 2026-08-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='tier',
            field=models.CharField(choices=[('none', 'No subscription'), ('Base', 'base'), ('Advanced', 'advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('none', 'No subscription'), ('Base', 'base'), ('Advanced', 'advanced')], default='none', max_length=20),
        ),
    ]
