# Generated by Django 6.0.3 on 2026-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_promocode_tier_alter_usersubscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='duration_days',
            field=models.IntegerField(choices=[(7, '7 days'), (30, '1 month'), (90, '3 months')]),
        ),
    ]
