# Generated by Django 6.0.3 on 2026-09-05 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_promocode_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='duration_days',
            field=models.IntegerField(choices=[(7, '7 days'), (30, '1 month'), (90, '3 months'), (180, 'half year'), (365, '365 days')]),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='tier',
            field=models.CharField(choices=[('none', 'No subscription'), ('base', 'Base'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('none', 'No subscription'), ('base', 'Base'), ('advanced', 'Advanced')], default='none', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['none', 'base', 'advanced'])), name='valid_promo_tier'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__in', [7, 30, 90, 180, 365])), name='valid_promo_duration'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('tier__in', ['none', 'base', 'advanced'])), name='valid_subscription_tier'),
        ),
    ]
