# Generated by Django 5.2.1 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('item_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemlisting')),
            ],
            options={
                'indexes': [models.Index(fields=['item_listing', '-time_stamp'], name='price_histo_item_li_ac1c5b_idx'), models.Index(fields=['time_stamp'], name='price_histo_time_st_e9425d_idx')],
            },
        ),
    ]
