# Generated by Django 6.0.3 on 2026-07-05 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0007_itemlisting_fee_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('alert_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notify_telegram', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('marketplaces', models.ManyToManyField(blank=True, to='items.marketplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'item'], name='tracking_tr_user_id_07ff91_idx')],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
